name: lmgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - open-clip-torch
  - cudatoolkit
  - plyfile
  - python
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - opencv
  - tensorboard
  - jaxtyping
  - matplotlib
  - typing
  - pathlib
  - open3d
  - pytorch3d
  - lpips
  - trimesh
  - pip:
      - submodules/segment-anything-langsplat
      - submodules/langsplat-rasterization
      - submodules/simple-knn
      - PGSR/submodules/diff-plane-rasterization